##
## Astra.conf configuration file. Lines beginning with # are comments.
##

addnode=Astrad.westus.cloudapp.azure.com
addnode=Astrap.westus.cloudapp.azure.com
addnode=Astrag.westus.cloudapp.azure.com
addnode=Astras.westus.cloudapp.azure.com
addnode=Astrac.westus.cloudapp.azure.com
addnode=Astra1.westus.cloudapp.azure.com
addnode=Astra2.westus.cloudapp.azure.com
addnode=Astra3.westus.cloudapp.azure.com

rpcuser=RandomName
rpcpassword=SuperSecretRandomPasswordChangeOrBePwned
rpcport=51473
rpcallowip=127.0.0.1
rpcconnect=127.0.0.1
daemon=1

## mnAstraaddress=D97SEoJDksK1NieZuuFP85JGpFkzPY1rnj